In [1]:
from argparse import Namespace
import time
import os
import sys
import numpy as np
from PIL import Image
import torch
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
!pip install aiogram==2.14

In [2]:
#@title Setup Repository
import os
os.chdir('/content')
CODE_DIR = 'encoder4editing'

!git clone https://github.com/omertov/encoder4editing.git $CODE_DIR
!wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
#!sudo unzip ninja-linux.zip -d /usr/local/bin/

!sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force
os.chdir(f'./{CODE_DIR}')

from argparse import Namespace
import time
import os
import sys
import numpy as np
from PIL import Image
import torch
import torchvision.transforms as transforms

sys.path.append(".")
sys.path.append("..")

from utils.common import tensor2im
from models.psp import pSp  # we use the pSp framework to load the e4e encoder.

%load_ext autoreload
%autoreload 2

!pip install gdown

file_id = '1cUv_reLE6k3604or78EranS7XzuVMWeO'
output_name = 'model.pth'

import gdown
gdown.download(f'https://drive.google.com/uc?id={file_id}', output_name, quiet=False)

import torch

model_path = output_name  # Path to the downloaded model file
ckpt = torch.load(model_path, map_location='cpu')

opts = ckpt['opts']
opts['checkpoint_path'] = model_path
opts= Namespace(**opts)
net = pSp(opts)
net.eval()
net.cuda()

fatal: destination path 'encoder4editing' already exists and is not an empty directory.
--2024-09-01 14:45:49--  https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/1335132/d2f252e2-9801-11e7-9fbf-bc7b4e4b5c83?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240901%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240901T144511Z&X-Amz-Expires=300&X-Amz-Signature=12b93079ff29f7930e2a6e327285f2bb6c945c2d95bfea459291c31512784f4e&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=1335132&response-content-disposition=attachment%3B%20filename%3Dninja-linux.zip&response-content-type=application%2Foctet-stream [following]
--2024-09-01 14:45:49--  https://objects.githubusercontent.com/git

/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(


Downloading...
From (original): https://drive.google.com/uc?id=1cUv_reLE6k3604or78EranS7XzuVMWeO
From (redirected): https://drive.google.com/uc?id=1cUv_reLE6k3604or78EranS7XzuVMWeO&confirm=t&uuid=2787deae-1bc6-4507-bfe3-624262a9c1b6
To: /content/encoder4editing/model.pth
100%|██████████| 1.20G/1.20G [00:39<00:00, 30.1MB/s]
<ipython-input-2-acc4739f2bc3>:42: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serializ

Loading e4e over the pSp framework from checkpoint: model.pth


/content/encoder4editing/models/psp.py:44: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(self.opts.checkpoint_path, map_location='cpu')


pSp(
  (encoder): Encoder4Editing(
    (input_layer): Sequential(
      (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): PReLU(num_parameters=64)
    )
    (body): Sequential(
      (0): bottleneck_IR_SE(
        (shortcut_layer): MaxPool2d(kernel_size=1, stride=2, padding=0, dilation=1, ceil_mode=False)
        (res_layer): Sequential(
          (0): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (2): PReLU(num_parameters=64)
          (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
          (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (5): SEModule(
            (avg_pool): AdaptiveAvgPool2d(output_size=1)
            (fc1): Conv2d(64

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
!pip install ftfy regex tqdm
!pip install git+https://github.com/openai/CLIP.git

  Cloning https://github.com/openai/CLIP.git to /tmp/pip-req-build-itrkhimx
  Running command git clone --filter=blob:none --quiet https://github.com/openai/CLIP.git /tmp/pip-req-build-itrkhimx
  Resolved https://github.com/openai/CLIP.git to commit dcba3cb2e2827b402d2701e7e1c7d9fed8a20ef1
  Preparing metadata (setup.py) ... done


In [5]:
import torch
from model import Generator

g_ema = Generator(1024, 512, 8)

g_ema.load_state_dict(torch.load('/content/drive/MyDrive/stylegan2-ffhq-config-f (1).pt')["g_ema"], strict=False)
g_ema.eval()
g_ema = g_ema.cuda()

<ipython-input-5-f9c1fc8c0380>:6: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  g_ema.load_state_dict(torch.load('/content/drive/MyDrive/stylegan2-ffhq-config-f (1).pt')["g_

In [6]:
# Set the random seed
#torch.manual_seed(seed)

# Assuming g_ema is already defined and initialized
mean_latent = g_ema.mean_latent(4023)

latent_code_init_not_trunc = torch.randn(1, 512).cuda()
with torch.no_grad():
    img_orig, latent_code_init = g_ema([latent_code_init_not_trunc], return_latents=True,
                                        truncation=0.7, truncation_latent=mean_latent)


In [7]:
if 'shape_predictor_68_face_landmarks.dat' not in os.listdir():
    !wget http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2
    !bzip2 -dk shape_predictor_68_face_landmarks.dat.bz2
def run_alignment(image_path):
    import dlib
    from utils.alignment import align_face
    predictor = dlib.shape_predictor("shape_predictor_68_face_landmarks.dat")
    aligned_image = align_face(filepath=image_path, predictor=predictor)
    print("Aligned image has shape: {}".format(aligned_image.size))
    return aligned_image

def encode_path(path):

    input_image = run_alignment(path)
    transform_img = transforms.Compose([
            transforms.Resize((256, 256)),
            transforms.ToTensor(),
            transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])])
    transformed_image = transform_img(input_image)
    image, latent = net(transformed_image.unsqueeze(0).to("cuda").float(), randomize_noise=False, return_latents=True)
    return image[0], latent


In [14]:
import torch
from torchvision.utils import make_grid
from torchvision.transforms import ToPILImage
from aiogram import Bot, Dispatcher, executor, types
from io import BytesIO
from encoder4editing.models.stylegan2.model import Generator
from argparse import Namespace
import time
import numpy as np
from PIL import Image
import os
import math
import torchvision
from torch import optim
import clip
from id_loss import IDLoss
from clip_loss import CLIPLoss
import nest_asyncio
from aiogram.types import ContentType
nest_asyncio.apply()
args = Namespace()
args.description = 'blonde'
args.lr_rampup = 0.05
args.lr = 0.1
args.step = 20
args.l1_lambda = 0.005
args.l2_lambda = 0.008 # The weight for similarity to the original image.
args.save_intermediate_image_every = 1
args.results_dir = 'results'
args.ir_se50_weights = '/content/drive/MyDrive/model_ir_se50.pth'
args.stylegan_size = 1024
user_message = ""

# Initialize the bot and dispatcher
bot = Bot(token='7493418929:AAGvEbYAm-8_8F3hVbCkj6pe8_FIFXX5IvA')
dp = Dispatcher(bot)



# Load the StyleGAN2 model
g_ema = Generator(1024, 512, 8)
g_ema.load_state_dict(torch.load('/content/drive/MyDrive/stylegan2-ffhq-config-f (1).pt')["g_ema"], strict=False)
g_ema.eval()
g_ema = g_ema.cuda()

clip_loss = CLIPLoss(args)
def generate_random_image():
    # Set the random seed
    #torch.manual_seed(seed)

    # Assuming g_ema is already defined and initialized
    mean_latent = g_ema.mean_latent(4023)

    latent_code_init_not_trunc = torch.randn(1, 512).cuda()
    with torch.no_grad():
        img_orig, latent_code_init = g_ema([latent_code_init_not_trunc], return_latents=True,
                                           truncation=0.7, truncation_latent=mean_latent)

    return img_orig, latent_code_init



# Command handler for /start and /help
@dp.message_handler(commands=['start', 'help'])
async def welcome(message: types.Message):
    await message.reply("Hello, I'm a bot! I will help you to modify an image according some text. Use /random to generate a random image. Also, you can write /upload_image and after that upload a real image.")

img, latent_code_init = 0, 0
result_image = 0
# Command handler for /logo
@dp.message_handler(commands=['random'])
async def logo(message: types.Message):
    global img, latent_code_init, result_image
    img, latent_code_init = generate_random_image()
    await message.reply("Your randomly generated image:")
    # Convert the tensor to a PIL image
    result_image = ToPILImage()(make_grid(img.detach().cpu(), normalize=True, scale_each=True, padding=0))
    h, w = result_image.size
    resized_image = result_image.resize((h // 2, w // 2))
    # Save the image to a BytesIO object
    buffer = BytesIO()
    resized_image.save(buffer, format='PNG')
    buffer.seek(0)
    # Send the image

    await bot.send_photo(chat_id=message.chat.id, photo=buffer)
    await message.reply("Please enter your text:")

@dp.message_handler(commands=['upload_image'])
async def ask_for_photo(message: types.Message):
    await message.reply("Please send the image you want to upload.")


@dp.message_handler(content_types=ContentType.PHOTO)
async def handle_photo(message: types.Message):
    global latent_code_init
    # Get the file ID of the highest quality photo
    photo = message.photo[-1]
    photo_file_id = photo.file_id
    # Store the photo file ID in a variable or use it for further processing
    file_info = await bot.get_file(photo_file_id)
    downloaded_file = await bot.download_file(file_info.file_path)
    with open("downloaded_image.jpg", "wb") as f:
        f.write(downloaded_file.getvalue())

    result_image, latent_code_init = encode_path('/content/encoder4editing/downloaded_image.jpg')
    print(latent_code_init.shape)
    result_image = tensor2im(result_image)
    # Save the image to a BytesIO object
    buffer = BytesIO()
    result_image.save(buffer, format='PNG')
    buffer.seek(0)
    # Send the image

    await message.reply("Please enter your text:")


@dp.message_handler()
async def handle_message(message: types.Message):
    global result_image, latent_code_init
    user_message = message.text
    await message.reply(f'Please wait until your image will be generated')
    # Initialize the latent vector to be updated.


    latent = latent_code_init.detach().clone().requires_grad_(True)
    latent_code_init = latent_code_init.detach().clone()
    optimizer = optim.Adam([latent], lr=args.lr)

    def train():
        with torch.no_grad():
            img_orig, _ = g_ema([latent_code_init], input_is_latent=True, randomize_noise=False)

        # The learning rate adjustment function.
        def get_lr(t, initial_lr, rampdown=0.50, rampup=0.05):
            lr_ramp = min(1, (1 - t) / rampdown)
            lr_ramp = 0.5 - 0.5 * math.cos(lr_ramp * math.pi)
            lr_ramp = lr_ramp * min(1, t / rampup)

            return initial_lr * lr_ramp

        text_inputs = torch.cat([clip.tokenize(user_message)]).cuda()
        os.makedirs(args.results_dir, exist_ok=True)
        t1 = time.time()
        k = 0
        for i in range(args.step):
            # Adjust the learning rate.
            t = i / args.step
            lr = get_lr(t, args.lr)
            optimizer.param_groups[0]["lr"] = lr

            # Generate an image using the latent vector.
            img_gen, _ = g_ema([latent], input_is_latent=True, randomize_noise=False)
            # Calculate the loss value.
            c_loss = clip_loss(img_gen, text_inputs)
            l2_loss = ((latent_code_init - latent) ** 2).sum()

            id_loss = IDLoss(args)
            print('hi')
            i_loss = id_loss(img_gen, img_orig)[0]
            print('no')
            loss = c_loss + args.l2_lambda * l2_loss + args.l1_lambda * i_loss
            print(c_loss, args.l2_lambda * l2_loss, args.l1_lambda * i_loss)
            # Get gradient and update the latent vector.
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            k += 1
            # Log the current state.
            print(f"lr: {lr}, loss: {loss.item():.4f}, epoch:{k}")
            if args.save_intermediate_image_every > 0 and i % args.save_intermediate_image_every == 0:
                with torch.no_grad():
                    img_gen, _ = g_ema([latent], input_is_latent=True, randomize_noise=False)
                torchvision.utils.save_image(img_gen, f"results/{str(i).zfill(5)}.png", normalize=True)
            t2 = time.time()


        # Display the initial image and result image.
        final_result = torch.cat([img_orig, img_gen])
        torchvision.utils.save_image(final_result.detach().cpu(), os.path.join(args.results_dir, "final_result.jpg"),
                                     normalize=True, scale_each=True)
        return img_gen

    final_result = train()

    result_image = ToPILImage()(make_grid(final_result.detach().cpu(), normalize=True, scale_each=True, padding=0))
    h, w = result_image.size
    result_image.resize((h // 2, w // 2))

    await message.reply("Result image:")
    buffer = BytesIO()
    result_image.save(buffer, format='PNG')  # Save PIL Image to buffer
    buffer.seek(0)  # Rewind the buffer to the beginning

    # Send the image
    await bot.send_photo(chat_id=message.chat.id, photo=buffer)


if __name__ == "__main__":
    executor.start_polling(dp, skip_updates=True)

<ipython-input-14-91aba4f83174>:42: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  g_ema.load_state_dict(torch.load('/content/drive/MyDrive/stylegan2-ffhq-config-f (1).pt')["

Aligned image has shape: (256, 256)
torch.Size([1, 18, 512])
Loading ResNet ArcFace
hi
no
tensor([[0.8330]], device='cuda:0', dtype=torch.float16,
       grad_fn=<RsubBackward1>) tensor(0., device='cuda:0', grad_fn=<MulBackward0>) tensor(0., device='cuda:0', grad_fn=<MulBackward0>)
lr: 0.0, loss: 0.8330, epoch:1
Loading ResNet ArcFace
hi
no
tensor([[0.8330]], device='cuda:0', dtype=torch.float16,
       grad_fn=<RsubBackward1>) tensor(0., device='cuda:0', grad_fn=<MulBackward0>) tensor(5.9605e-10, device='cuda:0', grad_fn=<MulBackward0>)
lr: 0.1, loss: 0.8330, epoch:2
Loading ResNet ArcFace
hi
no
tensor([[0.7500]], device='cuda:0', dtype=torch.float16,
       grad_fn=<RsubBackward1>) tensor(0.7336, device='cuda:0', grad_fn=<MulBackward0>) tensor(0.0014, device='cuda:0', grad_fn=<MulBackward0>)
lr: 0.1, loss: 1.4844, epoch:3
Loading ResNet ArcFace
hi
no
tensor([[0.7485]], device='cuda:0', dtype=torch.float16,
       grad_fn=<RsubBackward1>) tensor(0.2652, device='cuda:0', grad_fn=<MulBa